### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by isaacsas** [isaacsas/ReactionNetworkImporters.jl#22]

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

Release notes:

Please see the HISTORY.md file for breaking changes in this version.

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
